import Head from 'next/head'
import { IPost } from '../core/interfaces/IPost';
import { getPostsList } from '../core/service/PostsService';
import { ReactElement } from 'react';
import PostItem from '../ui/PostItem/PostItem';

const News = ({ posts }: {posts :IPost[]}): ReactElement => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
        <meta name="theme-color" content="#fdfaf6"/>
      </Head>

      <main>
        {posts.map((post:IPost)=> {
          return (
            <div key={post.slug}>
              <PostItem title={post.title} uri={post.uri} excerpt={post.excerpt} slug={post.slug}
                        featuredImage={post.featuredImage} author={post.author} date={post.date} key={post.slug}/>
            </div>
          )
        })}
      </main>
    </>
  )
}


export async function getStaticProps(): Promise<{ props: { posts: IPost[] } }> {
  const posts = await getPostsList()
  return  {
    props: {
      posts
    }
  };
}

export default News
