import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { IPost } from '../core/interfaces/IPost';
import { getPostsList } from '../core/service/PostsService';
import { ReactElement } from 'react';

const Home = ({ posts }: {posts :IPost[]}): ReactElement => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        {posts.map((post:IPost)=> {
          return (
            <div key={post.title}>
              <h2>{post.title}</h2>
              <div dangerouslySetInnerHTML={{__html: post.excerpt}}></div>
              <img srcSet={post.featuredImage.srcSet} width={'100%'}></img>
            </div>
          )
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps(): Promise<{ props: { posts: IPost[] } }> {
  const posts = await getPostsList()
  return  {
    props: {
      posts
    }
  };
}

export default Home
